import { describe, expect, test } from 'bun:test'
import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'

const projectFile = (path: string) => resolve(process.cwd(), path)
const readProjectFile = (path: string) => readFile(projectFile(path), 'utf8')

const TEXT_BEARING_MASTERS = [
  'assets/brand/keepindex-wordmark-dark.svg',
  'assets/brand/keepindex-wordmark-light.svg',
  'assets/brand/keepindex-lockup.svg',
  'assets/brand/keepindex-domain-lockup.svg',
  'assets/brand/social-card.svg',
] as const

const COLOR_MARK_ASSETS = [
  'assets/brand/keepindex-mark.svg',
  'assets/brand/keepindex-wordmark-dark.svg',
  'assets/brand/keepindex-wordmark-light.svg',
  'assets/brand/keepindex-lockup.svg',
  'assets/brand/social-card.svg',
  'public/keepindex-icon.svg',
  'public/keepindex-maskable-icon.svg',
] as const

describe('KeepIndex vector identity', () => {
  test('outlines visible lettering without host-font dependencies', async () => {
    for (const path of TEXT_BEARING_MASTERS) {
      const source = await readProjectFile(path)
      expect(source).toContain('Generated by scripts/generate-brand-vectors.mjs')
      expect(source).not.toMatch(/<text\b/)
      expect(source).not.toContain('font-family=')
      expect(source).toMatch(/<path\b/)
    }
  })

  test('keeps the canonical protected weave in every color mark', async () => {
    for (const path of COLOR_MARK_ASSETS) {
      const source = await readProjectFile(path)
      expect(source).toContain('M29 29h6v6h-6z')
      expect(source).toContain('M30 32h4')
    }
  })

  test('uses the documented evidence-green token for the domain', async () => {
    const source = await readProjectFile('assets/brand/keepindex-domain-lockup.svg')
    expect(source).toContain('#62D66B')
    expect(source).not.toContain('#238A48')
  })

  test('preserves natural spacing between the large green domain-suffix glyphs', async () => {
    const source = await readProjectFile('assets/brand/keepindex-domain-lockup.svg')
    const suffix = source.match(
      /<g fill="#62D66B" transform="translate\([^\"]+\) scale\(0\.104 -0\.104\)">([\s\S]*?)<\/g>/,
    )?.[1]
    const advances = [...(suffix ?? '').matchAll(/transform="translate\(([-\d.]+) [-\d.]+\)"/g)]
      .map((match) => Number(match[1]))
    const gaps = advances.slice(1).map((advance, index) => advance - advances[index]!)

    expect(advances).toHaveLength(4)
    expect(gaps).toEqual([222.5, 272.75, 625.25])
  })
})
